[package]
name = "sudo-rs"
description = "Memory safe implementation of sudo and su"
readme = "README.md"
version = "0.2.0-dev.20230711"
license = "Apache-2.0 OR MIT"
edition = "2021"
repository = "https://github.com/memorysafety/sudo-rs"
homepage = "https://github.com/memorysafety/sudo-rs"
publish = true
categories = ["command-line-interface"]

rust-version = "1.70"

resolver = "2"

default-run = "sudo"

[lib]
path = "src/lib.rs"

[[bin]]
name = "sudo"
path = "bin/sudo.rs"

[[bin]]
name = "su"
path = "bin/su.rs"

[[bin]]
name = "visudo"
path = "bin/visudo.rs"

[dependencies]
libc = "0.2.127"
glob = "0.3.0"
log = { version = "0.4.11", features = ["std"] }

[dev-dependencies]
pretty_assertions = "1.2.1"

[features]
default = []
dev = []

[profile.release]
strip = "debuginfo"
lto = true
opt-level = "s"

[package.metadata.deb]
name = "sudo-rs"
copyright = "Copyright (c) 2022-2023 Internet Security Research Group"
conflicts = "sudo"
replaces = "sudo"
provides = "sudo"
maintainer = "Ruben Nijveld <ruben@tweedegolf.com>"
maintainer-scripts = "../pkg/deb"
changelog = "pkg/deb/changelog"
assets = [
    ["target/release/sudo", "usr/bin/sudo", "755"],
    ["target/release/visudo", "usr/bin/visudo", "755"],
    ["docs/man/sudo.8", "usr/share/man/man8/sudo.8", "644"],
    ["docs/man/visudo.8", "usr/share/man/man8/visudo.8", "644"],
]

[package.metadata.generate-rpm]
license = "ASL 2.0 OR MIT"
assets = [
    { source = "target/release/sudo", dest = "/usr/bin/sudo", mode = "755" },
    { source = "target/release/visudo", dest = "/usr/bin/visudo", mode = "755" },
    { source = "docs/man/sudo.8", dest = "/usr/share/man/man8/sudo.8", mode = "644", doc = true },
    { source = "docs/man/visudo.8", dest = "/usr/share/man/man8/visudo.8", mode = "644", doc = true },
]
conflicts = "sudo"
provides = "sudo"
