[workspace]
members = [
  "sudo",
  "test-binaries",
  "lib/sudo-cli",
  "lib/sudo-common",
  "lib/sudo-cutils",
  "lib/sudo-system",
  "lib/sudoers",
  "lib/sudo-defaults",
  "lib/sudo-pam-sys",
  "lib/sudo-pam",
]
default-members = ["sudo"]
