[package]
name = "sudo-rs"
version = "0.1.0-alpha.1"
license = "Apache-2.0 OR MIT"
edition = "2021"
repository = "https://github.com/memorysafety/sudo-rs"
homepage = "https://github.com/memorysafety/sudo-rs"
publish = true
categories = ["command-line-interface"]

resolver = "2"

default-run = "sudo"

[lib]
path = "src/lib.rs"

[[bin]]
name = "sudo"
path = "bin/sudo.rs"

[[bin]]
name = "su"
path = "bin/su.rs"

[dependencies]
libc = "0.2.139"
glob = "0.3.1"
signal-hook = { version = "0.3.15", features = ["extended-siginfo"] }
signal-hook-registry = "1.4.1"
log = "0.4.17"
env_logger = { version = "0.9.3", default-features = false }

[dev-dependencies]
pretty_assertions = "1.3.0"
tempfile = "3.5.0"

[features]
default = []
dev = []

[profile.release]
strip = "debuginfo"
lto = true
opt-level = "s"
panic = "abort"
