[workspace]
members = [
  "sudo",
  "test-binaries",
  "lib/sudo-cli",
  "lib/sudo-common",
  "lib/sudo-cutils",
  "lib/sudo-system",
  "lib/sudoers",
  "lib/sudo-defaults",
  "lib/sudo-pam-sys",
  "lib/sudo-pam",
]
default-members = ["sudo"]

[workspace.package]
version = "0.1.0-alpha.1"
license = "Apache-2.0 OR MIT"
edition = "2021"
repository = "https://github.com/memorysafety/sudo-rs"
homepage = "https://github.com/memorysafety/sudo-rs"
publish = true

[workspace.dependencies]
clap = "4.0.32"
libc = "0.2.139"
thiserror = "1.0.38"
which = "4.4.0"
rpassword = "7.2.0"
glob = "0.3.1"
sha2 = "0.10.6"
digest = "0.10.6"

# Test only dependencies
pretty_assertions = "1.3.0"

# Build time dependencies
bindgen = "0.63.0"

sudo-cli = { version = "0.1.0-alpha.1", path = "./lib/sudo-cli" }
sudo-pam = { version = "0.1.0-alpha.1", path = "./lib/sudo-pam" }
sudo-system = { version = "0.1.0-alpha.1", path = "./lib/sudo-system" }
sudo-pam-sys = { version = "0.1.0-alpha.1", path = "./lib/sudo-pam-sys" }
sudo-cutils = { version = "0.1.0-alpha.1", path = "./lib/sudo-cutils" }
sudo-common = { version = "0.1.0-alpha.1", path = "./lib/sudo-common" }
sudo-defaults = { version = "0.1.0-alpha.1", path = "./lib/sudo-defaults" }
sudoers = { version = "0.1.0-alpha.1", path = "./lib/sudoers" }

[package.metadata.generate-rpm]
assets = [
  { source = "target/release/sudo", dest = "/usr/bin/sudo-rs", mode = "755" },
]