[package]
name = "sudo"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
readme.workspace = true
description.workspace = true
categories = ["command-line-interface"]

[dependencies]
sudo-common.workspace = true
sudo-system.workspace = true
sudo-cli.workspace = true
sudoers.workspace = true
sudo-pam.workspace = true

[package.metadata.deb]
# All paths must be relative to the workspace root, i.e. ../
name = "sudo-rs"
copyright = "Copyright (c) 2022-2023 Internet Security Research Group"
maintainer = "Prossimo (ISRG) <sudo-rs-maintainer@memorysafety.org>"
maintainer-scripts = "pkg/deb/"
breaks = "sudo"
replaces = "sudo"

[package.metadata.generate-rpm]
# See: https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Good_Licenses
license = "ASL 2.0"
assets = [
  { source = "target/release/sudo", dest = "/usr/bin/sudo-rs", mode = "755" },
]
conflicts = "sudo"