[package]
name = "sudo"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true
categories = ["command-line-interface"]

[dependencies]
sudo-common.workspace = true
sudo-system.workspace = true
sudo-cli.workspace = true
sudoers.workspace = true
sudo-pam.workspace = true

[package.metadata.deb]
copyright = "Copyright (c) 2022-2023 Internet Security Research Group"
maintainer = "Prossimo (ISRG) <sudo-rs-maintainer@memorysafety.org>"
extended-description-file = "../README.md"
maintainer-scripts = "../pkg/deb/"

[package.metadata.generate-rpm]
assets = [
  { source = "target/release/sudo", dest = "/usr/bin/sudo-rs", mode = "755" },
]
