name: Packaging

on:
  push:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: binutils-x86-64-linux-gnu binutils-arm-linux-gnueabihf binutils-aarch64-linux-gnu
          version: "1.0"
      - name: Add cargo-deb
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deb
      - name: Add cargo-generate-rpm
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-generate-rpm
      - name: Add cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "stable"
      - name: Build
        run: cross build --release --locked --target ${{matrix.target}}
      - name: Create deb package
        run: cargo deb --no-build --target ${{matrix.target}}
      - uses: actions/upload-artifact@v3
        with:
          name: deb-${{matrix.target}}
          path: target/${{matrix.target}}/debian/
