name: Packaging

on:
  push:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add cargo-deb
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deb
      - name: Add cargo-generate-rpm
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-generate-rpm

