name: Packaging

on:
  push:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
    steps:
      - uses: actions/checkout@v2
      - name: Add cargo-deb
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deb
      - name: Add cargo-generate-rpm
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-generate-rpm
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: "${{matrix.target}}"
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "stable"
      - name: Build
        run: cargo build --release --locked
